### PR TITLE
Revamp issue creation options

### PR DESCRIPTION
**Pull request by Pandapip1**
[Documentation for the `.github/ISSUE_TEMPLATE/config.yml` file](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)

### CODE REVIEW

**Comment by Pandapip1** [comment]
Bump; CC @abmiguez

**Comment by kescobo** [comment]
@sagun98 I think good to close this once you roll out https://github.com/biobakery/biobakery/pull/53

**Comment by kescobo** [comment]
@Pandapip1 Yeah, the idea is that the template in `biobakery` is going to be rolled out to other repos

**Comment by Pandapip1** [comment]
> @Pandapip1 Yeah, the idea is that the template in biobakery is going to be rolled out to other repos

I've already submitted a PR to update the template in biobakery ;)

**Comment by Pandapip1** [comment]
@kescobo my PR to update the biobakery template was merged (https://github.com/biobakery/biobakery/pull/55). Now that this PR simply has the effect of bringing the configuration in line with the template, can it be merged?

**Comment by kescobo** [comment]
Not my place to merge, but seems fine to me 👍

**Pull request closed without merging**
